#!/bin/sh

SCRIPT_ABS_PATH=$(readlink -f "$0")
SCRIPT_ABS_DIR=$(dirname $SCRIPT_ABS_PATH)
SCRIPT="$SCRIPT_ABS_DIR/joern-server/target/universal/stage/bin/joern-server"

echo $SCRIPT
if [ ! -f "$SCRIPT" ]; then
    echo "You need to run 'sbt stage' first";
    exit 1;
fi;

$SCRIPT
