#!/bin/sh

SCRIPT_ABS_PATH=$(readlink -f "$0")
SCRIPT_ABS_DIR=$(dirname $SCRIPT_ABS_PATH)
SCRIPT="$SCRIPT_ABS_DIR/joern-cli/target/universal/stage/bin/joern-query"

LOG4J_FILENAME="$SCRIPT_ABS_DIR/joern-cli/src/main/resources/log4j2.xml"
export JAVA_OPTS="-Dlog4j.configurationFile=$LOG4J_FILENAME $JAVA_OPTS"

if [ ! -f "$SCRIPT" ]; then
    echo "You need to run 'sbt stage' first";
    exit 1;
fi;

$SCRIPT $@
