addSbtPlugin("com.simplytyped" % "sbt-antlr4"           % "0.8.3")
addSbtPlugin("com.github.sbt"  % "sbt-native-packager"  % "1.11.1")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("io.shiftleft"    % "sbt-ci-release-early" % "2.1.2")
addSbtPlugin("com.github.sbt"  % "sbt-dynver"           % "5.1.0")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"         % "0.14.2")
