addSbtPlugin("com.simplytyped" % "sbt-antlr4"           % "0.8.3")
addSbtPlugin("com.github.sbt"  % "sbt-native-packager"  % "1.10.0")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"         % "3.10.0")
addSbtPlugin("com.github.sbt"  % "sbt-pgp"              % "2.2.1")
addSbtPlugin("com.github.sbt"  % "sbt-dynver"           % "5.0.1")
