load("//bazel:scala.bzl", "scala_library")

scala_library(
    name = "io_shiftleft_codepropertygraph_with_deps",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:io_joern_flatgraph_core_3",
        "@maven//:io_joern_flatgraph_help_3",
        "@maven//:io_shiftleft_codepropertygraph_3",
    ],
    deps = [
    ],
)

scala_library(
    name = "com_lihaoyi_upickle_with_deps",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:com_lihaoyi_ujson_3",
        "@maven//:com_lihaoyi_upickle_3",
    ],
    deps = [
    ],
)
