name: Upload Container image

on:
  schedule:
    - cron: "0 8 * * *" # run once daily
  workflow_dispatch:    # allow to manually trigger this workflow

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    if: github.repository_owner == 'joernio'
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            ghcr.io/joernio/joern

      - name: Build and push Docker images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ci/Dockerfile.alma
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=joern
          cache-to: type=gha,mode=max,scope=joern

      - name: Extract metadata (tags, labels) for Docker
        id: meta3
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            ghcr.io/joernio/joern-slim

      - name: Build and push Docker images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ci/Dockerfile.slim
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta3.outputs.tags }}
          labels: ${{ steps.meta3.outputs.labels }}
          cache-from: type=gha,scope=joern-slim
          cache-to: type=gha,mode=max,scope=joern-slim

      - name: Extract metadata (tags, labels) for Docker
        id: meta2
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            ghcr.io/joernio/joern-alma8

      - name: Build and push Docker images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ci/Dockerfile.alma8
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
          cache-from: type=gha,scope=joern-alma8
          cache-to: type=gha,mode=max,scope=joern-alma8
