name: master
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  test:
    concurrency: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 2.7
      - name: Set up Swift
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 # v1.14.0
        with:
          swift-version: "6.1"
      - name: Install Bundler
        run: gem install bundler -v 2.4.22
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          components: rust-src
      - run: sbt scalafmtCheck test
      - name: Test distribution
        run: |
          python -m pip install requests pexpect
          sbt joerncli/stage querydb/createDistribution
          python -u ./testDistro.py
