name: master
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  test:
    concurrency: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Bundler
        run: gem install bundler
      - name: Delete `.rustup` directory
        run: rm -rf /home/runner/.rustup # to save disk space
        if: runner.os == 'Linux'
      - name: Delete `.cargo` directory # to save disk space
        run: rm -rf /home/runner/.cargo
        if: runner.os == 'Linux'
      - run: sbt scalafmtCheck +test
      - run: ./testDistro.sh
      - run: |
          cd joern-cli/target/universal/stage
          ./schema-extender/test.sh
          cd -
