name: master
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  test:
    concurrency: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@f6db8ab474efba716fc7f04441ab33714e4825af # v1.5.4
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 2.7
      - name: Set up Swift
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 # v1.14.0
        with:
          swift-version: "6.1"
      - name: Install Bundler
        run: gem install bundler -v 2.4.22
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rust-src
      - run: sbt scalafmtCheck test
      - name: Test distribution
        run: |
          python -m pip install requests pexpect
          sbt joerncli/stage querydb/createDistribution
          python -u ./testDistro.py
