name: upgrade-deps
# Nightly job that verifies that we can upgrade all internal dependencies
# This essentially runs `./updateDependencies.sh --non-interactive` and
# runs the regular tests, to notify us if some upstream dependency
# introduced breaking changes. If it's red, that's not the end of the
# world, but we should get it back on track to unblock others. 
on: 
  schedule:
    - cron: '0 2 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Set up Swift
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 # v1.14.0
        with:
          swift-version: "6.1"
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          components: rust-src
      - uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Upgrade all (internal) dependencies
        run: ./updateDependencies.sh --non-interactive
      - run: sbt clean test
      - name: Test distribution
        run: |
          python -m pip install requests pexpect
          sbt joerncli/stage querydb/createDistribution
          python -u ./testDistro.py
